### ISSUE TITLE
Steampunk Armor Does Not Work Correctly

### ISSUE THREAD

**Issue by 0BLIQU3** [Luke100000/ImmersiveArmors#12]
Mods Installed:
Immersive Armors 1.1.0 Forge
JEI
Neat

1. Steampunk Leggings do not actually do anything; It appears that the 10% damage increase actually only occurs when the Steampunk Boots are equipped. Tested via punch attacks on animals, with 1.1 damage being dealt with the boots on and 1 damage being dealt with the boots off and the leggings on.

2. Steampunk Boots do not negate fall damage as advertised. While particle effects are shown to be in effect and fall speed is slightly reduced, there is actually no reduction to fall damage occurring. Tested via falling from high points with the steampunk boots on vs wearing iron boots, with equal amounts of damage being taken.

3. Steampunk Armor appears to potentially INCREASE the amount of damage taken from explosions rather than reduce it like what it says in the tooltip. Comparisons were done in three scenarios: With full steampunk armor, with full iron armor, and with no armor at all. With a distance of 4 blocks between the player and a block of TNT, the following damage values where recorded: ~8 1/2 hearts (no armor), ~4 hearts (full iron), instant death (full steampunk). Another test with a 6 block distance with just iron vs steampunk armor had iron armor take about 1/2 hearts worth of damage and steampunk armor resulting in a whopping 6 hearts of damage. This does not seem to be intentional, at least not the disparity between the item description and its actual function.

4. No, the compass on your shoulder doesn't work :( While it does certainly change the direction it points in, it actually does not point to the spawnpoint at all. In my world, it appeared to point southeast and continued to do so for thousands of blocks.

**Comment by Luke100000** [comment]
1) Whoops, you are right, fixed

2) Minecraft moment right here, fall damage is in fact not caused by velocity. Will fix that, a shame it slipped through my testing.

3) I can not confirm this issue. I also compared the steampunk with the iron armor, with 5 hearts vs 7 damage respectively on a direct creeper hit. No armor killed me. TNT experiment with 4 blocks resulted in 5 hearts with iron, 4 with steampunk and 9 without armor. Explosion resistance uses the vanilla mechanics. Dedicated or integrated server?

4) The compass works for me, but I notices its mirrored XD will fix this. Also, notice its orientation is head based rather than using the bodies orientation, which I can not fix.

Thanks for your detailed issue!

**Comment by 0BLIQU3** [comment]
Upon further testing, it seems that Steampunk does actually block more explosion damage than iron when it comes to creeper explosions, but as for TNT, I'm still finding that I take even more damage than when unarmored. Tested mainly with a TNT block ~4 blocks away and while it did about 7 1/2 hearts of damage while unarmored and 4 hearts with full iron armor, it was still instant death with full steampunk armor on.
I am testing this all on a singleplayer world.


Edit: Tested again with just a chestplate (first no armor, then iron, then steam) and ended up with taking 7 1/2 hearts without armor like usual, 7 hearts of damage with an iron chestplate, and dying with a steampunk chestplate on.
This was done in version 1.1.1 and the other changes made work perfectly fine (:

**Comment by Luke100000** [comment]
I'm clueless, but I doubled resistance for now. Maybe that helps
