### ISSUE TITLE
1.20.1 Port

### ISSUE THREAD

**Issue by itsdinkd** [Luke100000/ImmersiveArmors#92]

**Comment by seb303** [comment]
I'll enhance this issue with some actual words..... ;)

Are there plans to update to 1.20.1?
Is there a timeline for this?

Thank you.

**Comment by itsdinkd** [comment]
Needless words, I created this for a request, not for questions.

**Comment by Luke100000** [comment]
It's called being nice, and without any questions or actual issue there is no need to clutter the issues. I am fully aware of Mojangs progress myself.

**Comment by seb303** [comment]
Hi @Luke100000,
I can quite understand you not wanting to clutter the issues.  But would it still be possible to know your plans or estimated timing regarding 1.20.1 support please?  I ask because we will shortly be launching a 1.20.1 modded SMP and would like to include your mod from the start if possible (adding mods later is a bit of a pain for everyone to update).
I couldn't see this info anywhere, hence asking here.
Thank you,
Seb

**Comment by Luke100000** [comment]
> 

Whoops, forgot to link that commit here, but update dropped 2 hours ago :)

**Comment by itsdinkd** [comment]
> It's called being nice, and without any questions or actual issue there is no need to clutter the issues. I am fully aware of Mojangs progress myself.

You'd be surprised how many devs are not. 

Asking you a question like when are you going to release something is nice? I guess certain people have different meanings of the word nice.
